#!/bin/bash

tmp=$(mktemp)

new () {
  while IFS= read -r line; do
    if [[ $line =~ ^\Shortcut\| ]];then
      break
    fi
    echo "$line"
  done < README.md
  echo "Shortcut|Bookmark"
  echo "-|-"
  yq e '.[] | "`" + .B + "` | [" + .T + "](" + .L + ")"' data.yml | tac
}

new > "${tmp}"
mv "${tmp}" README.md
